name: Cloudflared Connector
version: "1.1.0"
slug: cloudflared_connector
description: Connector for a Cloudflare Tunnel that is managed in the Zero Trust dashboard
url: https://github.com/heidrickla/ha-cloudflared-connector
arch:
  - amd64
  - aarch64
startup: services
boot: auto
init: false
stage: stable
advanced: false
options:
  tunnel_token: ""
  loglevel: info
schema:
  tunnel_token: password
  loglevel: list(debug|info|warn|error)?
